version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: wsgi_app
    restart: always
    expose:
      - 8000
    environment:
      - ENV=testing

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./nginx/nginx_proxy.conf:/etc/nginx/nginx.conf
